export enum TodoActionTypes {
  SET_TODOS = "SET_TODOS",
  ADD_TODO = "ADD_TODO",
}

export enum GetTodosType {
  GET_TODOS_REQUEST = "GET_TODOS_REQUEST",
  GET_TODOS_SUCCESS = "GET_TODOS_SUCCESS",
  GET_TODOS_FAILURE = "GET_TODOS_FAILURE",
}

export enum PostTodoType {
  POST_TODO_REQUEST = "POST_TODO_REQUEST",
  POST_TODO_SUCCESS = "POST_TODO_SUCCESS",
  POST_TODO_FAILURE = "POST_TODO_FAILURE",
}
