export enum TodoActionTypes {
  SET_TODOS = "SET_TODOS",
}

export enum GetTodosType {
  GET_TODOS_REQUEST = "GET_TODOS_REQUEST",
  GET_TODOS_SUCCESS = "GET_TODOS_SUCCESS",
  GET_TODOS_FAILURE = "GET_TODOS_FAILURE",
}
